# Generated by Django 4.2 on 2023-04-15 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionesmodels',
            name='amigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_amigo_reverse', to='home.amigomodels'),
        ),
        migrations.AlterField(
            model_name='notificacionesmodels',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_noti', to='home.likemodels'),
        ),
        migrations.AlterField(
            model_name='notificacionesmodels',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_notificaciones_reverce', to='home.solisitudmodel'),
        ),
        migrations.AlterField(
            model_name='notificacionesmodels',
            name='solicitud_enviada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_enviada', to='home.amigomodels'),
        ),
        migrations.AlterField(
            model_name='notificacionesmodels',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_reverce', to=settings.AUTH_USER_MODEL),
        ),
    ]
