# Generated by Django 4.2 on 2023-04-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='archivo',
            field=models.FileField(upload_to='static/archivos'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/archivos'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/archivos'),
        ),
    ]
