# Generated by Django 4.2 on 2023-04-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_notificacionesmodels_amigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionesmodels',
            name='comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comentariosreverse', to='home.comentarmodels'),
        ),
    ]
